services:
  - type: web
    name: crowd-counter
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install torch --index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
      python -c "from ultralytics import YOLO; YOLO('yolov8n.pt')"
    startCommand: gunicorn app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 180 --keep-alive 5 --max-requests 100 --max-requests-jitter 10 --log-level debug --bind 0.0.0.0:$PORT
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      cpu: 1x
      memory: 2048MB
      storage: 2048MB
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TIMEOUT_SECONDS
        value: 180
      - key: PYTORCH_ENABLE_MPS_FALLBACK
        value: 1
      - key: CUDA_VISIBLE_DEVICES
        value: ""
      - key: OMP_NUM_THREADS
        value: 2
      - key: MKL_NUM_THREADS
        value: 2
      - key: MALLOC_TRIM_THRESHOLD_
        value: 65536
    autoDeploy: false